In [2]:
# Importing dependencies

from learntools.core import binder
import numpy as np
import string
import pandas as pd
from itertools import groupby
binder.bind(globals())

from learntools_ex import *

print("Setup Complete")

Setup Complete


## **Questions**

### **IMPORTANT**: You **don't** have to delete any `q{n}.check()` or `q{n}.hint()` or `q{n}_sol = question_{n}()`. Please make sure that the function name and function signature match the question and the example given. Additionally, all functions should be runnable or your solution will not be evaluated.

## **Q1:** Create a one-dimensional NumPy array of the numbers from 5 to 905, counting by 10?

In [7]:
def question_1():
    q1_sol = np.arange(5, 905, 10)
    print(q1_sol)
    return q1_sol
    #return NotImplementedError #Sorry I don't know what this line does, so I made it commented


q1_sol = question_1()
q1.check()

[  5  15  25  35  45  55  65  75  85  95 105 115 125 135 145 155 165 175
 185 195 205 215 225 235 245 255 265 275 285 295 305 315 325 335 345 355
 365 375 385 395 405 415 425 435 445 455 465 475 485 495 505 515 525 535
 545 555 565 575 585 595 605 615 625 635 645 655 665 675 685 695 705 715
 725 735 745 755 765 775 785 795 805 815 825 835 845 855 865 875 885 895]


<IPython.core.display.Javascript object>

<span style="color:#33cc33">Correct</span>

## **Q2**: Create the same NumPy array using a Python range and a list? (Hint: create a list)

In [9]:
def question_2():
    q2_sol = np.array([i for i in range(5, 905, 10)])
    return q2_sol
    #raise NotImplementedError #Sorry I don't know what does this line do, so I made it commented


q2_sol = question_2()
q2.check()

<IPython.core.display.Javascript object>

<span style="color:#33cc33">Correct</span>

## **Q3**: How might you create a NumPy array of the capital letters, A-Z? (Hint: Ever heard of string.ascii_uppercase?)

In [42]:
def question_3():
    q3_sol = np.array(list(string.ascii_uppercase)) # have to import string (don't need to write "from numpy import string" again as it already existed)
    return q3_sol
    #raise NotImplementedError #Sorry I don't know what does this line do, so I made it commented


q3_sol = question_3()
q3.check()

<IPython.core.display.Javascript object>

<span style="color:#33cc33">Correct</span>

## **Q4**: Create a ten-element NumPy array object of all zeros and a six-element NumPy array object of all ones.

In [43]:
def question_4() -> tuple:
    # Expected: return (sol1, sol2)
    q4_sol_1 = np.zeros(10)
    q4_sol_2 = np.ones(6)
    return (q4_sol_1, q4_sol_2)
    #raise NotImplementedError
q4_sol_1, q4_sol_2 = question_4()
q4.check()

<IPython.core.display.Javascript object>

<span style="color:#33cc33">Correct</span>

## **Q5**: Given an 2-D array, print the third column.

In [10]:
input = np.array([[11, 22, 33], [44, 55, 66], [77, 88, 99]])


def question_5(input):
    q5_sol = input[:, -1]
    return q5_sol
    #raise NotImplementedError


q5_sol = question_5(input)
q5.check()

<IPython.core.display.Javascript object>

<span style="color:#33cc33">Correct</span>

## **Q6**: Create an array of the shape (3, 4), filled with 64-bit integer zeros.

In [23]:
def question_6():
    q6_sol = np.zeros((3, 4), dtype=np.int64)
    return (q6_sol)
    #raise NotImplementedError

q6_sol = question_6()
q6.check()

<IPython.core.display.Javascript object>

<span style="color:#33cc33">Correct</span>

## **Q7**: Split an array into 3 equal-sized sub-arrays.

In [27]:
input = np.arange(7, 34, 1).reshape(9, 3)



def question_7(input):
    # Expected: return (q7_sol_1, q7_sol_2, q7_sol_3)
    #input = input.reshape(3, 9)
    q7_sol = np.split(input, 3)
    print(q7_sol)
    return q7_sol
    
    #raise NotImplementedError


q7_sol_1, q7_sol_2, q7_sol_3 = question_7(input)
q7.check()

[array([[ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15]]), array([[16, 17, 18],
       [19, 20, 21],
       [22, 23, 24]]), array([[25, 26, 27],
       [28, 29, 30],
       [31, 32, 33]])]


<IPython.core.display.Javascript object>

<span style="color:#33cc33">Correct</span>

## **Q8**: Return the last 2 elements by each of the first rows of the (3,4) array. 

In [43]:
input = np.arange(1, 13, 1).reshape(3, 4)


def question_8(input):
    print (input)
    q8_sol = input[:2, -2:]
    return (q8_sol)
    #raise NotImplementedError


q8_sol = question_8(input)
q8.check()

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


<IPython.core.display.Javascript object>

<span style="color:#33cc33">Correct</span>

## **Q9**: Return how many elements are greater than 5 in an array.

In [46]:
input = np.arange(1, 13, 1).reshape(3, 4)


def question_9(input):
    print (input)
    q9_sol = np.count_nonzero(input > 5)
    return (q9_sol)
    #raise NotImplementedError


q9_sol = question_9(input)
q9.check()

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


<IPython.core.display.Javascript object>

<span style="color:#33cc33">Correct</span>

## **Q10**: Delete the second column from an array and insert the following new column in the same place.

In [ ]:
input = np.array([[34, 72, 33], [82, 22, 32], [59, 84, 10]])
insert_data = np.array([[37, 37, 37]])


def question_10(input, insert_data):
    print(input)
    q10_sol = np.delete(input, 1, 1)
    print(q10_sol)
    q10_sol = np.insert(q10_sol, 1, insert_data, axis = 1)
    print(q10_sol) # print to check if it's correct or not
    return q10_sol
    #raise NotImplementedError


q10_sol = question_10(input, insert_data)
q10.check()

[[34 72 33]
 [82 22 32]
 [59 84 10]]
[[34 33]
 [82 32]
 [59 10]]
[[34 37 33]
 [82 37 32]
 [59 37 10]]


<IPython.core.display.Javascript object>

<span style="color:#33cc33">Correct</span>

## **Q11**: Compute the Euclidean distance between each pair of consecutive points in a given 2D NumPy array and append the result as a new column.

Euclidian distance between two points $(x_1, y_1)$ and $(x_2, y_2)$ is $\sqrt{(x_2 - x_1)^2 + (y_2 - y_1)^2}$.  

In [ ]:
input = np.array([[1, 2], [4, 6], [7, 8], [10, 10]])


def question_11(input):
    print(input)
    diff = np.diff(input, axis = 0)
    print(diff)

    eucludian = np.sqrt(np.sum(diff**2, axis = 1))
    eucludian_col = np.append(eucludian, 0)[:, np.newaxis] # add 0 not nan, I spent nearly 1 hour to find out, maybe not everyone does the same, but quite interesting to know. Thank you!
    q11_sol = np.hstack((input, eucludian_col))
    print(q11_sol)
    return q11_sol
    #raise NotImplementedError

q11_sol = question_11(input)
q11.check()

[[ 1  2]
 [ 4  6]
 [ 7  8]
 [10 10]]
[[3 4]
 [3 2]
 [3 2]]
[[ 1.          2.          5.        ]
 [ 4.          6.          3.60555128]
 [ 7.          8.          3.60555128]
 [10.         10.          0.        ]]


<IPython.core.display.Javascript object>

<span style="color:#33cc33">Correct</span>

## **Q12**: Remove consecutive duplicates from a NumPy array.

In [67]:
input = np.array([[1, 1], [2, 1], [3, 3], [3, 3], [2, 1], [1, 1]])

def question_12(input):
    array = np.ones(len(input))
    print(array)
    mask = np.ones(len(input), dtype=bool)
    print(mask)
    mask[1:] = ~(np.all(input[1:] == input[:-1], axis=1))
    print(mask)
    q12_sol = input[mask]
    print(q12_sol)
    return q12_sol
    #raise NotImplementedError

q12_sol = question_12(input)
q12.check()

[1. 1. 1. 1. 1. 1.]
[ True  True  True  True  True  True]
[ True  True  True False  True  True]
[[1 1]
 [2 1]
 [3 3]
 [2 1]
 [1 1]]


<IPython.core.display.Javascript object>

<span style="color:#33cc33">Correct</span>

## **Q13**: Given a 2D NumPy array representing strokes, normalize all rows by subtracting the mean of each column and dividing by the standard deviation, but avoid division by zero.
$X_{\text{normalized}} = \frac{X - \mu}{\sigma}$

In [8]:
input = np.array([[10, 20, 30], [15, 24, 33], [8, 18, 29], [14, 22, 32]])

def question_13(input):
    print(input)
    mean_value = np.mean(input, axis = 0)
    print(mean_value)
    stdev = np.std(input, axis = 0)
    print(stdev)
    
    q13_sol = (input - mean_value) / stdev
    print(q13_sol)

    return q13_sol
    #raise NotImplementedError


q13_sol = question_13(input)
q13.check()

[[10 20 30]
 [15 24 33]
 [ 8 18 29]
 [14 22 32]]
[11.75 21.   31.  ]
[2.86138079 2.23606798 1.58113883]
[[-0.61159284 -0.4472136  -0.63245553]
 [ 1.13581527  1.34164079  1.26491106]
 [-1.31055608 -1.34164079 -1.26491106]
 [ 0.78633365  0.4472136   0.63245553]]


<IPython.core.display.Javascript object>

<span style="color:#33cc33">Correct</span>

## **Q14**: Delete the second column from an array and insert a new column at the same position where each value is the sum of its corresponding row.

In [16]:
input = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])


def question_14(input):
    print(input)
    new_2nd_col = np.sum(input, axis = 1)
    print(new_2nd_col)
    new_array = np.delete(input, 1, axis = 1)
    print(new_array)
    q13_sol = np.insert(new_array, 1, new_2nd_col, axis = 1)
    print(q13_sol)
    return q13_sol

    #raise NotImplementedError


q14_sol = question_14(input)
q14.check()

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[ 6 15 24]
[[1 3]
 [4 6]
 [7 9]]
[[ 1  6  3]
 [ 4 15  6]
 [ 7 24  9]]


<IPython.core.display.Javascript object>

<span style="color:#33cc33">Correct</span>

## **Q15**: Extract Unique Characters from a NumPy Array of Strings
Given a 1D NumPy array of strings, extract all unique characters present in the array and sort by their ASCII values.

In [13]:
input = np.array(["hello", "world", "numpy", "rocks"])


def question_15(input):
    q15_sol = set(sorted("".join(input)))
    print(q15_sol)
    return q15_sol
    #raise NotImplementedError


q15_sol = question_15(input)
q15.check()

{'m', 'c', 'p', 'k', 'e', 'w', 'n', 'y', 'r', 'd', 'o', 'l', 's', 'u', 'h'}


<IPython.core.display.Javascript object>

<span style="color:#33cc33">Correct</span>

## **Q16**: Generate a dictionary that maps each unique character to a unique index starting with 0, sorted by ascending ASCII value.

In [3]:
input = np.array(["a", "b", "c", "d", "a", "c", "e"])


def question_16(input):
    x = "".join(input)
    unique = sorted(set(x))
    q16_sol = {char: index for index, char in enumerate(unique)}

    print(q16_sol)
    return q16_sol
    #raise NotImplementedError


q16_sol = question_16(input)
q16.check()

{'a': 0, 'b': 1, 'c': 2, 'd': 3, 'e': 4}


<IPython.core.display.Javascript object>

<span style="color:#33cc33">Correct</span>

## **Q17**: Convert a List of 2D traces into a Single NumPy Array
Given a list of 2D traces (each being a NumPy array of shape `(N, 2)`), stack them into a single NumPy array.

In [17]:
input = [np.array([[1, 2], [3, 4]]), np.array([[5, 6], [7, 8], [9, 10]])]


def question_17(input):
    
    print(f"Original: {input[0]}")

    q17_sol = np.concatenate((input[0], input[1]), axis = 0)
    print(q17_sol)
    return q17_sol
    #return None
    #raise NotImplementedError


q17_sol = question_17(input)
q17.check()

Original: [[1 2]
 [3 4]]
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]


<IPython.core.display.Javascript object>

<span style="color:#33cc33">Correct</span>

## **Q18**: Convert a List of Text Labels into a NumPy Array of Integer Encodings
Given a vocabulary dictionary and a string of space-separated labels, convert the text into a NumPy array of indices.

In [64]:
input = {
    "hello": 0,
    "numpy": 1,
    "rocks": 2,
    "world": 3,
    "python": 4,
    "data": 5,
    "science": 6,
}

labels = "hello rocks"

def question_18(input, labels):
    lst_words = labels.split(" ")

    print(lst_words[0])
    for j in range(len(lst_words)):
        temp = lst_words[j]
        print(input[temp])
        lst_words[j] = input[temp]
    q18_sol = np.array(lst_words)
    print(q18_sol)
    return q18_sol
    
    #return None    
    #raise NotImplementedError


q18_sol = question_18(input, labels)
q18.check()

hello
0
2
[0 2]


<IPython.core.display.Javascript object>

<span style="color:#33cc33">Correct</span>

## **Q19**: Extract Non-Zero Differences from an Array
Given a NumPy array of first-order differences, extract only non-zero differences using masking.

In [ ]:
input = np.array([[3, 4], [0, 0], [-2, 1]])


def question_19(input):
   mask = input != 0
   input_test = input[mask]
   print(input_test)

   mask_q19 = np.all(input != 0, axis=1)
   print(mask_q19)
   q19_sol = input[mask_q19]
   print(q19_sol)
   return q19_sol
   #raise NotImplementedError


q19_sol = question_19(input)
q19.check()

[ 3  4 -2  1]
[ True False  True]
[[ 3  4]
 [-2  1]]


<IPython.core.display.Javascript object>

<span style="color:#33cc33">Correct</span>

## **Q20**: Time Series Data Transformation and Feature Engineering

### *Problem Statement:*  
You are given a time series dataset representing sensor readings from multiple devices. Each row consists of sensor values at a specific timestamp. Your task is to preprocess and extract meaningful features from the dataset by performing the following transformations:

### *Steps to Follow:*
1. Normalize Each Sensor Reading  
- Subtract the mean and divide by the standard deviation for each column.  
- Avoid division by zero by replacing std=0 with 1.  
2. Detect and Mask Anomalous Values
- If a sensor reading is more than 2.5 standard deviations away from the mean, replace it with NaN.
3. Interpolate Missing Values (NaN Handling)
- Fill NaN values with the average of the nearest non-NaN neighbors.
4. Extract First-Order Differences
- Compute the difference between consecutive time steps for each sensor.
5. Add a Binary Column for Missing Data
- Stack All Features into a Final Matrix
Create a new column `missing_flag` that is `1` where original data was `NaN`, otherwise `0`.
6. Stack All Features into a Final Matrix
- The final dataset should have normalized values, moving averages, first-order differences, and the missing flag.

In [11]:
input = np.array(
    [
        [1.0, 10.0, 100.0],
        [2.0, 20.0, 200.0],
        [3.0, 30.0, 10000.0],  # Outlier in third column
        [4.0, 40.0, 400.0],
        [5.0, 50.0, 500.0],
    ]
)


def question_20(input):
    print(input)
#----------------------------------------#
#  Normalize Each Sensor Reading  #
    mean_val = np.mean(input, axis = 0)
    print(mean_val)

    std_dev = np.std(input, axis = 0)
    std_dev[std_dev == 0] = 1
    print(std_dev)

    normalized_input = (input - mean_val) / std_dev
    print(normalized_input)    
#-----------------------------------------------------#
# Detect and Mask Anomalous Values #
    mask = np.abs(normalized_input) > 2.5
    print(mask)
    Anomalous_Values = np.where(mask, np.nan, input)
    print(Anomalous_Values)

# Interpolate Missing Values (NaN Handling) #
    interpolated_matrix = np.where(np.isnan(Anomalous_Values), np.nanmean(Anomalous_Values, axis = 0), Anomalous_Values)
    print(interpolated_matrix)

# Extract First-Order Differences #
    timeSteps_diff = np.diff(interpolated_matrix, axis = 0)
    timeSteps_diff_padded = np.vstack(
    (timeSteps_diff, np.zeros((1, timeSteps_diff.shape[1])))
)
    print(timeSteps_diff_padded)

# Create a new column `missing_flag` that is `1` where original data was `NaN`, otherwise `0` #
    missing_flag_col = np.isnan(Anomalous_Values).astype(int)
    print(missing_flag_col)

# Stack All Features into a Final Matrix #
    q20_sol = np.hstack([Anomalous_Values, timeSteps_diff_padded, missing_flag_col])
    print(q20_sol)
    return q20_sol
    #raise NotImplementedError



q20_sol = question_20(input)
q20.check()

[[1.e+00 1.e+01 1.e+02]
 [2.e+00 2.e+01 2.e+02]
 [3.e+00 3.e+01 1.e+04]
 [4.e+00 4.e+01 4.e+02]
 [5.e+00 5.e+01 5.e+02]]
[   3.   30. 2240.]
[1.41421356e+00 1.41421356e+01 3.88257646e+03]
[[-1.41421356 -1.41421356 -0.55118039]
 [-0.70710678 -0.70710678 -0.52542429]
 [ 0.          0.          1.99867281]
 [ 0.70710678  0.70710678 -0.47391211]
 [ 1.41421356  1.41421356 -0.44815602]]
[[False False False]
 [False False False]
 [False False False]
 [False False False]
 [False False False]]
[[1.e+00 1.e+01 1.e+02]
 [2.e+00 2.e+01 2.e+02]
 [3.e+00 3.e+01 1.e+04]
 [4.e+00 4.e+01 4.e+02]
 [5.e+00 5.e+01 5.e+02]]
[[1.e+00 1.e+01 1.e+02]
 [2.e+00 2.e+01 2.e+02]
 [3.e+00 3.e+01 1.e+04]
 [4.e+00 4.e+01 4.e+02]
 [5.e+00 5.e+01 5.e+02]]
[[ 1.0e+00  1.0e+01  1.0e+02]
 [ 1.0e+00  1.0e+01  9.8e+03]
 [ 1.0e+00  1.0e+01 -9.6e+03]
 [ 1.0e+00  1.0e+01  1.0e+02]
 [ 0.0e+00  0.0e+00  0.0e+00]]
[[0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]]
[[ 1.0e+00  1.0e+01  1.0e+02  1.0e+00  1.0e+01  1.0e+02  0.0e+00  0.0e+

<IPython.core.display.Javascript object>

<span style="color:#33cc33">Correct</span>